[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
frontend = { path = "../frontend" }
ir = { path = "../ir" }
passes = { path = "../passes" }
riscv-backend = { path = "../riscv-backend" }
